import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { ShieldCheck, Lock, FileText, CheckCircle2 } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Privacy Policy & Student Data Protection — LessonPlanner AI',
  description: 'Our commitment to educator privacy and zero student data collection. FERPA, COPPA, and CSPC compliant.',
};

export default function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16 space-y-10">
      <div className="border-b border-slate-200 pb-6">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-teal-50 text-teal-800 border border-teal-200 mb-3">
          <ShieldCheck className="w-3.5 h-3.5 text-teal-700" />
          <span>Student & Teacher Privacy Commitment</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
          Privacy Policy & Data Standards
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 mt-2">
          Last Updated: September 2026 • Compliant with FERPA, COPPA, and Student Privacy Pledge standards.
        </p>
      </div>

      {/* Summary Highlight */}
      <div className="p-6 rounded-2xl bg-teal-50/80 border border-teal-200 text-teal-950 text-sm space-y-2">
        <span className="font-bold text-xs uppercase tracking-wider text-teal-800 block">
          Plain-English Privacy Summary
        </span>
        <p className="leading-relaxed">
          LessonPlanner AI is built specifically for teachers. We never require, collect, or store student names, ID numbers, or academic records. All lesson planning, worksheet building, and rubric calculations execute with privacy in mind. We do not sell user data to advertising brokers.
        </p>
      </div>

      <div className="space-y-8 text-sm text-slate-700 leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900">1. Student Privacy (FERPA & COPPA Compliance)</h2>
          <p>
            The Family Educational Rights and Privacy Act (FERPA) and Children’s Online Privacy Protection Act (COPPA) protect student education records and online data. LessonPlanner AI does not collect student Personally Identifiable Information (PII).
          </p>
          <ul className="list-disc list-inside space-y-1.5 pl-2 text-slate-600">
            <li>Our tools do not require student user accounts, logins, or roster syncs.</li>
            <li>Worksheets generated by teachers provide standard blank lines for physical handwritten completion or upload to your school&apos;s secure learning management system (LMS).</li>
            <li>We do not create behavioral profiles of minors.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900">2. Information We Collect from Educators</h2>
          <p>
            When you interact with our website, we may collect minimal non-sensitive information necessary to deliver our services:
          </p>
          <ul className="list-disc list-inside space-y-1.5 pl-2 text-slate-600">
            <li><strong>Voluntary Form Submissions:</strong> If you subscribe to our teacher newsletter or submit an inquiry through our Contact page, we store your provided email address and message.</li>
            <li><strong>Aggregated Usage Analytics:</strong> We collect anonymous metrics (such as the most frequently requested grade levels or subjects) to improve curriculum templates. No curriculum content is linked to individual identities.</li>
            <li><strong>Local Browser Storage:</strong> Temporary preferences (such as selected grade level or rubric layout toggles) may be preserved in your device&apos;s browser memory so you don&apos;t lose work when refreshing.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900">3. Teacher Intellectual Property Ownership</h2>
          <p>
            Unlike many commercial platforms that claim licenses over user-created materials, <strong>you retain 100% copyright and intellectual property rights</strong> to any lesson plan, worksheet, or rubric you produce using our tools. You are free to publish, distribute to colleagues, photocopy for students, or upload to curriculum marketplaces.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900">4. Third-Party Services & Data Sharing</h2>
          <p>
            We do not sell, rent, or trade educator personal information to third-party data brokers. We only use reputable infrastructure partners (such as secure cloud hosting) bound by strict confidentiality terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900">5. Contact Our Privacy Officer</h2>
          <p>
            If you or your school district&apos;s compliance committee require a formal Data Privacy Agreement (DPA) or National Data Privacy Agreement (NDPA) exhibit, please contact us:
          </p>
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs space-y-1 text-slate-800">
            <div><strong>Email:</strong> privacy@lessonplanner.ai</div>
            <div><strong>Subject Line:</strong> District DPA Inquiry</div>
            <div><strong>Location:</strong> Austin, TX, United States</div>
          </div>
        </section>
      </div>
    </div>
  );
}
